package com.manuel.red.utils

object Constants {
    const val PACKAGE_NAME = "com.manuel.red"
    const val COLL_PACKAGE_SERVICE = "Packages Services"
    const val COLL_CONTRACTS_REQUESTED = "Contract Requests"
    const val COLL_USERS = "Users"
    const val COLL_TOKENS = "Tokens"
    const val PATH_CHATS = "Chats"
    const val PROP_TOKEN = "token"
    const val PROP_ID = "id"
    const val ACTION_INTENT = "action_intent"
    const val PROP_DATE = "date"
    const val PROP_USER_ID = "userId"
    const val PROP_STATUS = "status"
    const val PROP_AVAILABLE = "available"
    const val USER_PROP_DISCOUNT = "discount_package_service"
    const val PATH_PACKAGE_SERVICE_IMAGES = "package_service_images"
    const val PATH_PROFIlE = "profile"
    const val MY_IMAGE = "my_image"
    const val PROP_BODY = "body"
    const val PROP_TITLE = "title"
    const val TERMS_AND_CONDITIONS = "https://firebase.google.com/terms?authuser=0"
    const val PRIVACY_POLICY = "https://www.google.com/policies/privacy/?authuser=0"
}