package com.manuel.red.utils

object Constants {
    const val COLL_PACKAGE_SERVICE = "PackagesServices"
    const val COLL_CONTRACTS_REQUESTED = "ContractRequests"
    const val COLL_USERS = "Users"
    const val COLL_TOKENS = "Tokens"
    const val PATH_CHATS = "Chats"
    const val PROP_USERNAME = "username"
    const val PROP_TOKEN = "token"
    const val PROP_PROFILE_PICTURE = "profilePicture"
    const val PROP_ID = "id"
    const val PROP_USER_ID = "userId"
    const val PROP_STATUS = "status"
    const val PROP_AVAILABLE = "available"
    const val PROP_BODY = "body"
    const val PROP_TITLE = "title"
    const val PROP_IS_OFFER_AND_PROMO_DAY = "isOfferAndPromotionDay"
    const val PROP_OFFER_AND_PROMO_COUNTER = "offerAndPromotionCounter"
    const val PROP_PERCENTAGE = "percentage"
    const val PROP_IMAGE_PATH = "imagePath"
    const val PROP_MESSAGE = "message"
    const val PROP_LAST_MODIFICATION = "lastModification"
    const val PROP_REQUESTED = "requested"
    const val PROP_CHECK_CONTRACT_STATUS = "check_contract_status"
    const val PROP_ID_PACKAGE_SERVICE = "id_package_service"
    const val PROP_WITH_DISCOUNT = "with_discount"
    const val PROP_WITHOUT_DISCOUNT = "without_discount"
    const val ACTION_INTENT = "action_intent"
    const val USER_PROP_DISCOUNT = "discount_package_service"
    const val PATH_PACKAGE_SERVICE_IMAGES = "package_service_images"
    const val PATH_PROFIlE = "profile"
    const val MY_IMAGE = "my_image"
    const val TERMS_AND_CONDITIONS = "https://firebase.google.com/terms?authuser=0"
    const val PRIVACY_POLICY = "https://www.google.com/policies/privacy/?authuser=0"
    const val EMAIL = "appsmanuel1219@gmail.com"
    const val PASSWORD = "e12171922M/"
}